CREATE TABLE `call_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`callId` varchar(128) NOT NULL,
	`operatorId` varchar(64),
	`operatorName` varchar(128),
	`scenarioId` varchar(64),
	`scenarioName` varchar(256),
	`proceso` enum('COBROS','ATENCION','RECLAMACIONES','GESTION SINGULAR','FACTURACION','CONTRATACION','DESCONOCIDO') DEFAULT 'DESCONOCIDO',
	`priority` enum('P0','P1') DEFAULT 'P0',
	`adherenceScore` decimal(5,2),
	`sentimentScore` decimal(5,2),
	`correctnessScore` decimal(5,2),
	`speedScore` decimal(5,2),
	`averageScore` decimal(5,2),
	`status` varchar(64),
	`feedback` text,
	`areasMejora` text,
	`fortalezas` text,
	`criticalIssues` text,
	`durationSeconds` int,
	`evaluatedAt` timestamp,
	`rawClaudeResponse` text,
	`expectedWrapup` text,
	`expectedSteps` text,
	`airtableRecordId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `call_evaluations_id` PRIMARY KEY(`id`),
	CONSTRAINT `call_evaluations_callId_unique` UNIQUE(`callId`)
);
